[workspace]
changelog_update = false
git_release_enable = false
git_tag_enable = false
release_always = true

[[package]]
name = "cf-integration"
semver_check = true
git_release_enable = true
git_release_draft = true
git_release_latest = false
git_release_name = "v{{ version }}"
git_tag_enable = true
git_tag_name = "v{{ version }}"
