//! Native Goose load runner for MCP streamable HTTP.

use std::collections::HashSet;
use std::fmt;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::time::Duration;

use anyhow::{Context, Result, bail};
use goose::config::GooseConfiguration;
use goose::metrics::{GooseMetrics, GooseRequestMetric};
use goose::prelude::{
    GooseAttack, GooseMethod, GooseRequest, GooseUser, Scenario, Transaction, TransactionError,
    TransactionFunction, TransactionResult,
};
use reqwest::StatusCode;
use reqwest::header::{CONTENT_TYPE, HeaderMap};
use reqwest::redirect::Policy;
use serde_json::{Value, json};
use thiserror::Error;
use url::Url;

use cf_integration_platform::StackMode;
use cf_integration_platform::config::AppConfig;

use cf_integration_mcp::backend_identity::BackendIdentity;
use cf_integration_mcp::mcp::{
    ACCEPT, PROTOCOL_VERSION, initialize_with_id_and_version, is_stateless_protocol,
    jsonrpc_with_id, parse_mcp_body, routing_name, stateless_jsonrpc_with_id, tool_call_args,
};

use super::LoadSettings;

const MAX_RESPONSE_BODY_BYTES: usize = 8 * 1024 * 1024;
const REQUEST_TIMEOUT: Duration = Duration::from_secs(60);

/// Files generated by a Goose load run.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GooseReportPaths {
    html: PathBuf,
    json: PathBuf,
}

impl GooseReportPaths {
    /// Returns the HTML report path.
    #[must_use]
    pub fn html(&self) -> &Path {
        &self.html
    }

    /// Returns the machine-readable JSON report path.
    #[must_use]
    pub fn json(&self) -> &Path {
        &self.json
    }
}

#[derive(Clone)]
struct BearerToken(String);

impl BearerToken {
    fn expose(&self) -> &str {
        &self.0
    }
}

impl fmt::Debug for BearerToken {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("[REDACTED]")
    }
}

/// Fully resolved, credential-safe configuration for a Goose MCP load run.
#[derive(Clone)]
pub struct GooseLoadConfig {
    host: String,
    endpoint: String,
    users: usize,
    hatch_rate: f64,
    run_time: String,
    reports: GooseReportPaths,
    bearer_token: BearerToken,
    require_dataplane_backend: bool,
    protocol_version: String,
}

impl fmt::Debug for GooseLoadConfig {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("GooseLoadConfig")
            .field("host", &self.host)
            .field("endpoint", &self.endpoint)
            .field("users", &self.users)
            .field("hatch_rate", &self.hatch_rate)
            .field("run_time", &self.run_time)
            .field("reports", &self.reports)
            .field("bearer_token", &self.bearer_token)
            .field("require_dataplane_backend", &self.require_dataplane_backend)
            .field("protocol_version", &self.protocol_version)
            .finish()
    }
}

impl GooseLoadConfig {
    /// Resolves a mode-specific Goose run and creates its report directory.
    ///
    /// # Errors
    ///
    /// Returns an error for an empty token, missing dataplane server ID, invalid
    /// public base URL, unsupported duration, or report-directory failure.
    pub fn new(
        config: &AppConfig,
        mode: StackMode,
        settings: &LoadSettings,
        bearer_token: &str,
        server_id: Option<&str>,
    ) -> Result<Self> {
        Self::new_with_protocol_version(
            config,
            mode,
            settings,
            bearer_token,
            server_id,
            PROTOCOL_VERSION,
        )
    }

    /// Resolves a Goose run with an explicit MCP protocol version.
    ///
    /// # Errors
    ///
    /// Returns the same errors as [`Self::new`] and rejects an empty protocol
    /// version.
    pub fn new_with_protocol_version(
        config: &AppConfig,
        mode: StackMode,
        settings: &LoadSettings,
        bearer_token: &str,
        server_id: Option<&str>,
        protocol_version: &str,
    ) -> Result<Self> {
        if bearer_token.trim().is_empty() {
            bail!("Goose bearer token must not be empty");
        }
        if protocol_version.trim().is_empty() {
            bail!("Goose MCP protocol version must not be empty");
        }

        let host = normalized_host(
            config
                .base_url()
                .value
                .to_str()
                .context("MCP_CLI_BASE_URL must be valid UTF-8")?,
        )?;
        let (mode_name, endpoint) = match mode {
            StackMode::Controlplane => ("controlplane", String::from("/mcp")),
            StackMode::Dataplane => {
                let server_id = server_id
                    .filter(|value| !value.trim().is_empty())
                    .context("dataplane Goose server ID must not be empty")?;
                ("dataplane", dataplane_endpoint(server_id)?)
            }
        };
        let report_dir = config
            .integration_dir()
            .join("reports/load")
            .join(mode_name)
            .join("goose");
        fs::create_dir_all(&report_dir)
            .with_context(|| format!("failed to create Goose report directory {report_dir:?}"))?;

        Ok(Self {
            host,
            endpoint,
            users: settings.users().get(),
            hatch_rate: settings.spawn_rate(),
            run_time: goose_run_time(settings.run_time())?,
            reports: GooseReportPaths {
                html: report_dir.join("goose-report.html"),
                json: report_dir.join("goose-report.json"),
            },
            bearer_token: BearerToken(bearer_token.to_owned()),
            require_dataplane_backend: mode == StackMode::Dataplane,
            protocol_version: protocol_version.to_owned(),
        })
    }

    /// Returns the normalized public stack origin.
    #[must_use]
    pub fn host(&self) -> &str {
        &self.host
    }

    /// Returns the public MCP request path.
    #[must_use]
    pub fn endpoint(&self) -> &str {
        &self.endpoint
    }

    /// Returns the configured concurrent-user count.
    #[must_use]
    pub fn users(&self) -> usize {
        self.users
    }

    /// Returns the users started per second.
    #[must_use]
    pub fn hatch_rate(&self) -> f64 {
        self.hatch_rate
    }

    /// Returns the Goose-compatible whole-second run time.
    #[must_use]
    pub fn run_time(&self) -> &str {
        &self.run_time
    }

    /// Returns the MCP protocol version emitted by each virtual user.
    #[must_use]
    pub fn protocol_version(&self) -> &str {
        &self.protocol_version
    }

    /// Returns both report paths.
    #[must_use]
    pub fn reports(&self) -> &GooseReportPaths {
        &self.reports
    }

    /// Builds a Goose configuration without consulting process arguments.
    #[must_use]
    pub fn goose_configuration(&self) -> GooseConfiguration {
        let mut configuration = GooseConfiguration::default();
        configuration.host.clone_from(&self.host);
        configuration.users = Some(self.users);
        configuration.increase_rate = Some(self.hatch_rate.to_string());
        configuration.run_time.clone_from(&self.run_time);
        configuration.no_reset_metrics = true;
        configuration.no_telnet = true;
        configuration.no_websocket = true;
        configuration.quiet = 1;
        configuration.report_file = vec![
            self.reports.html.to_string_lossy().into_owned(),
            self.reports.json.to_string_lossy().into_owned(),
        ];
        configuration
    }

    /// Executes the native Goose MCP scenario.
    ///
    /// # Errors
    ///
    /// Returns an error when Goose cannot execute, reports expose a credential,
    /// or any request or transaction metric records a failure.
    pub async fn execute(self) -> std::result::Result<GooseRunOutcome, GooseRunError> {
        let reports = self.reports.clone();
        let configuration = self.goose_configuration();
        let bearer_token = self.bearer_token.clone();
        let shared = Arc::new(SharedRunConfig {
            endpoint: self.endpoint,
            bearer_token: bearer_token.clone(),
            require_dataplane_backend: self.require_dataplane_backend,
            protocol_version: self.protocol_version,
        });
        let scenario = build_scenario(shared).map_err(|source| GooseRunError::Execution {
            source,
            reports: reports.clone(),
        })?;
        let metrics = GooseAttack::initialize_with_config(configuration)
            .map_err(|source| GooseRunError::Execution {
                source,
                reports: reports.clone(),
            })?
            .register_scenario(scenario)
            .execute()
            .await
            .map_err(|source| GooseRunError::Execution {
                source,
                reports: reports.clone(),
            })?;

        inspect_reports(&reports, bearer_token.expose(), &metrics).await?;

        let failed_requests = failed_request_count(&metrics);
        let failed_transactions = failed_transaction_count(&metrics);
        if failed_requests > 0 || failed_transactions > 0 {
            return Err(GooseRunError::FailedMetrics {
                failed_requests,
                failed_transactions,
                metrics: Box::new(metrics),
                reports,
            });
        }

        Ok(GooseRunOutcome { metrics, reports })
    }
}

/// Successful Goose result with metrics and diagnostic report locations.
#[derive(Debug)]
pub struct GooseRunOutcome {
    metrics: GooseMetrics,
    reports: GooseReportPaths,
}

impl GooseRunOutcome {
    /// Returns the complete Goose metrics.
    #[must_use]
    pub fn metrics(&self) -> &GooseMetrics {
        &self.metrics
    }

    /// Returns generated report locations.
    #[must_use]
    pub fn reports(&self) -> &GooseReportPaths {
        &self.reports
    }

    /// Returns failed request count.
    #[must_use]
    pub fn failed_requests(&self) -> usize {
        failed_request_count(&self.metrics)
    }

    /// Returns failed transaction count.
    #[must_use]
    pub fn failed_transactions(&self) -> usize {
        failed_transaction_count(&self.metrics)
    }
}

/// Fail-closed Goose execution errors retaining available diagnostics.
#[derive(Debug, Error)]
pub enum GooseRunError {
    /// Goose could not construct or execute the load attack.
    #[error("Goose execution failed; reports: {reports:?}")]
    Execution {
        /// Underlying Goose error.
        #[source]
        source: goose::GooseError,
        /// Intended or generated report locations.
        reports: GooseReportPaths,
    },
    /// Goose completed but recorded failed operations.
    #[error(
        "Goose recorded {failed_requests} failed requests and {failed_transactions} failed transactions; reports: {reports:?}"
    )]
    FailedMetrics {
        /// Number of failed requests.
        failed_requests: usize,
        /// Number of failed transactions.
        failed_transactions: usize,
        /// Complete metrics retained for diagnostics.
        metrics: Box<GooseMetrics>,
        /// Generated report paths.
        reports: GooseReportPaths,
    },
    /// A generated report could not be inspected for credential safety.
    #[error("failed to inspect Goose report {path:?}; reports: {reports:?}")]
    ReportInspection {
        /// Report that could not be read.
        path: PathBuf,
        /// Underlying read failure.
        #[source]
        source: io::Error,
        /// Complete metrics retained for diagnostics.
        metrics: Box<GooseMetrics>,
        /// Generated report paths.
        reports: GooseReportPaths,
    },
    /// A credential-bearing report could not be removed.
    #[error("failed to remove tainted Goose report {path:?}; reports: {reports:?}")]
    ReportCleanup {
        /// Credential-bearing report that could not be deleted.
        path: PathBuf,
        /// Underlying removal failure.
        #[source]
        source: io::Error,
        /// Complete metrics retained for diagnostics.
        metrics: Box<GooseMetrics>,
        /// Generated report paths.
        reports: GooseReportPaths,
    },
    /// A generated report contained the bearer credential and was removed.
    #[error("removed Goose report {path:?} because it contained a bearer credential")]
    CredentialLeak {
        /// Removed report path.
        path: PathBuf,
        /// Complete metrics retained for diagnostics.
        metrics: Box<GooseMetrics>,
        /// Generated report paths.
        reports: GooseReportPaths,
    },
}

#[derive(Clone)]
struct SharedRunConfig {
    endpoint: String,
    bearer_token: BearerToken,
    require_dataplane_backend: bool,
    protocol_version: String,
}

#[derive(Clone)]
struct UserSession {
    endpoint: String,
    bearer_token: BearerToken,
    session_id: Option<String>,
    ready: bool,
    callable_tools: Vec<String>,
    next_tool: usize,
    next_request_id: u64,
    require_dataplane_backend: bool,
    protocol_version: String,
}

impl fmt::Debug for UserSession {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("UserSession")
            .field("endpoint", &self.endpoint)
            .field("bearer_token", &self.bearer_token)
            .field("session_id", &self.session_id.as_ref().map(|_| "[PRESENT]"))
            .field("ready", &self.ready)
            .field("callable_tools", &self.callable_tools)
            .field("next_tool", &self.next_tool)
            .field("next_request_id", &self.next_request_id)
            .field("require_dataplane_backend", &self.require_dataplane_backend)
            .field("protocol_version", &self.protocol_version)
            .finish()
    }
}

struct McpResponse {
    request: GooseRequestMetric,
    headers: HeaderMap,
    body: String,
}

#[derive(Clone, Copy)]
enum ExpectedStatus {
    Ok,
    Accepted,
    SessionDeleted,
}

fn build_scenario(
    shared: Arc<SharedRunConfig>,
) -> std::result::Result<Scenario, goose::GooseError> {
    let stateless = is_stateless_protocol(&shared.protocol_version);
    let initialize_config = Arc::clone(&shared);
    let initialize: TransactionFunction = Arc::new(move |user| {
        let config = Arc::clone(&initialize_config);
        Box::pin(async move {
            match initialize_user(user, &config).await {
                Ok(()) => Ok(()),
                Err(error)
                    if matches!(
                        error.as_ref(),
                        TransactionError::RequestFailed { .. } | TransactionError::Reqwest(_)
                    ) =>
                {
                    // Goose has already recorded the failed request. Keep the user
                    // dormant so the timed run can finish and the outer metrics gate
                    // can return a diagnostic-rich failure.
                    if let Some(state) = user.get_session_data_mut::<UserSession>() {
                        state.session_id = None;
                        state.ready = false;
                        state.callable_tools.clear();
                    }
                    Ok(())
                }
                Err(error) => Err(error),
            }
        })
    });

    let mut scenario = Scenario::new("MCP streamable HTTP").register_transaction(
        Transaction::new(initialize)
            .set_name(if stateless {
                "discover MCP server"
            } else {
                "initialize MCP session"
            })
            .set_on_start(),
    );
    scenario = scenario.register_transaction(
        transaction(list_tools)
            .set_name("list MCP tools")
            .set_weight(3)?,
    );
    scenario = scenario.register_transaction(
        transaction(call_tool)
            .set_name("call MCP tool")
            .set_weight(6)?,
    );
    if !stateless {
        scenario = scenario.register_transaction(
            transaction(ping_server)
                .set_name("ping MCP server")
                .set_weight(1)?,
        );
        scenario = scenario.register_transaction(
            transaction(delete_session)
                .set_name("delete MCP session")
                .set_on_stop(),
        );
    }
    Ok(scenario)
}

fn transaction(
    function: for<'a> fn(
        &'a mut GooseUser,
    ) -> std::pin::Pin<
        Box<dyn std::future::Future<Output = TransactionResult> + Send + 'a>,
    >,
) -> Transaction {
    let function: TransactionFunction = Arc::new(move |user| function(user));
    Transaction::new(function)
}

async fn initialize_user(user: &mut GooseUser, config: &SharedRunConfig) -> TransactionResult {
    user.set_client_builder(
        reqwest::Client::builder()
            .user_agent("cf-integration-goose/0.1")
            .redirect(Policy::none())
            .no_proxy()
            .timeout(REQUEST_TIMEOUT),
    )
    .await?;
    user.set_session_data(UserSession {
        endpoint: config.endpoint.clone(),
        bearer_token: config.bearer_token.clone(),
        session_id: None,
        ready: false,
        callable_tools: Vec::new(),
        next_tool: 0,
        next_request_id: 2,
        require_dataplane_backend: config.require_dataplane_backend,
        protocol_version: config.protocol_version.clone(),
    });

    let state = session(user)?.clone();
    let request_id = json!(1);
    let stateless = is_stateless_protocol(&config.protocol_version);
    let payload = if stateless {
        stateless_jsonrpc_with_id(
            "server/discover",
            None,
            request_id.clone(),
            &config.protocol_version,
        )
    } else {
        initialize_with_id_and_version(request_id.clone(), config.protocol_version.as_str())
    };
    let mut response = send_mcp_request(
        user,
        &state,
        GooseMethod::Post,
        Some(&payload),
        false,
        if stateless {
            "server/discover"
        } else {
            "initialize"
        },
        ExpectedStatus::Ok,
    )
    .await?;
    let result = match decode_result(&response, &request_id) {
        Ok(result) => result,
        Err(tag) => return fail_request(user, &mut response.request, tag),
    };
    if stateless {
        let supported = result
            .get("supportedVersions")
            .and_then(Value::as_array)
            .is_some_and(|versions| {
                versions
                    .iter()
                    .any(|version| version.as_str() == Some(config.protocol_version.as_str()))
            });
        if !supported
            || result
                .get("capabilities")
                .and_then(Value::as_object)
                .is_none()
            || result.get("resultType").and_then(Value::as_str).is_none()
            || result.get("cacheScope").and_then(Value::as_str).is_none()
            || result.get("ttlMs").and_then(Value::as_u64).is_none()
        {
            return fail_request(
                user,
                &mut response.request,
                "server/discover response is missing required stateless fields",
            );
        }
        session_mut(user)?.ready = true;
        return list_tools(user).await;
    }

    if result.get("protocolVersion").and_then(Value::as_str)
        != Some(config.protocol_version.as_str())
    {
        return fail_request(
            user,
            &mut response.request,
            "initialize returned an unexpected protocol version",
        );
    }
    if result
        .get("capabilities")
        .and_then(Value::as_object)
        .is_none()
    {
        return fail_request(
            user,
            &mut response.request,
            "initialize response is missing a capabilities object",
        );
    }
    let valid_server_info = result
        .get("serverInfo")
        .and_then(Value::as_object)
        .is_some_and(|server_info| {
            ["name", "version"].into_iter().all(|field| {
                server_info
                    .get(field)
                    .and_then(Value::as_str)
                    .is_some_and(|value| !value.is_empty())
            })
        });
    if !valid_server_info {
        return fail_request(
            user,
            &mut response.request,
            "initialize response is missing valid serverInfo name and version",
        );
    }
    let session_id = match response
        .headers
        .get("mcp-session-id")
        .and_then(|value| value.to_str().ok())
        .filter(|value| !value.trim().is_empty())
    {
        Some(value) => value.to_owned(),
        None => {
            return fail_request(
                user,
                &mut response.request,
                "initialize response is missing a valid MCP session ID",
            );
        }
    };
    let state = session_mut(user)?;
    state.session_id = Some(session_id);
    state.ready = true;

    let state = session(user)?.clone();
    let notification = json!({
        "jsonrpc": "2.0",
        "method": "notifications/initialized"
    });
    let _response = send_mcp_request(
        user,
        &state,
        GooseMethod::Post,
        Some(&notification),
        true,
        "initialized notification",
        ExpectedStatus::Accepted,
    )
    .await?;

    list_tools(user).await
}

fn list_tools(user: &mut GooseUser) -> transaction_future::TransactionFuture<'_> {
    Box::pin(async move {
        if !session(user)?.ready {
            return dormant_user().await;
        }
        let (state, request_id) = next_request(user)?;
        let payload = request_payload(&state, "tools/list", None, request_id.clone());
        let mut response = send_mcp_request(
            user,
            &state,
            GooseMethod::Post,
            Some(&payload),
            true,
            "tools/list",
            ExpectedStatus::Ok,
        )
        .await?;
        let result = match decode_result(&response, &request_id) {
            Ok(result) => result,
            Err(tag) => return fail_request(user, &mut response.request, tag),
        };
        let tools = match result.get("tools").and_then(Value::as_array) {
            Some(tools) => tools,
            None => {
                return fail_request(
                    user,
                    &mut response.request,
                    "tools/list result is missing its tools array",
                );
            }
        };
        let mut seen = HashSet::new();
        let mut callable_tools = Vec::new();
        for tool in tools {
            let Some(name) = tool
                .as_object()
                .and_then(|object| object.get("name"))
                .and_then(Value::as_str)
                .filter(|name| !name.is_empty())
            else {
                return fail_request(
                    user,
                    &mut response.request,
                    "tools/list contains a malformed tool entry",
                );
            };
            if tool_call_args(name).is_some() && seen.insert(name.to_owned()) {
                callable_tools.push(name.to_owned());
            }
        }
        if callable_tools.is_empty() {
            return fail_request(
                user,
                &mut response.request,
                "tools/list returned no explicitly safe callable tool",
            );
        }
        let state = session_mut(user)?;
        state.callable_tools = callable_tools;
        state.next_tool %= state.callable_tools.len();
        Ok(())
    })
}

fn call_tool(user: &mut GooseUser) -> transaction_future::TransactionFuture<'_> {
    Box::pin(async move {
        if !session(user)?.ready {
            return dormant_user().await;
        }
        let (state, request_id, name) = next_tool_call(user)?;
        let Some(arguments) = tool_call_args(&name) else {
            return Err(custom_error(
                "selected MCP tool is not on the safe allowlist",
            ));
        };
        let payload = request_payload(
            &state,
            "tools/call",
            Some(json!({"name": name, "arguments": arguments})),
            request_id.clone(),
        );
        let mut response = send_mcp_request(
            user,
            &state,
            GooseMethod::Post,
            Some(&payload),
            true,
            "tools/call",
            ExpectedStatus::Ok,
        )
        .await?;
        let result = match decode_result(&response, &request_id) {
            Ok(result) => result,
            Err(tag) => return fail_request(user, &mut response.request, tag),
        };
        if result.get("content").and_then(Value::as_array).is_none()
            || result
                .get("isError")
                .is_some_and(|value| value != &Value::Bool(false))
        {
            return fail_request(
                user,
                &mut response.request,
                "tools/call returned a malformed or failed result",
            );
        }
        Ok(())
    })
}

fn ping_server(user: &mut GooseUser) -> transaction_future::TransactionFuture<'_> {
    Box::pin(async move {
        if !session(user)?.ready {
            return dormant_user().await;
        }
        let (state, request_id) = next_request(user)?;
        let payload = jsonrpc_with_id("ping", None, request_id.clone());
        let mut response = send_mcp_request(
            user,
            &state,
            GooseMethod::Post,
            Some(&payload),
            true,
            "ping",
            ExpectedStatus::Ok,
        )
        .await?;
        if let Err(tag) = decode_result(&response, &request_id) {
            return fail_request(user, &mut response.request, tag);
        }
        Ok(())
    })
}

fn delete_session(user: &mut GooseUser) -> transaction_future::TransactionFuture<'_> {
    Box::pin(async move {
        let state = session(user)?.clone();
        if state.session_id.is_none() {
            return dormant_user().await;
        }
        let _response = send_mcp_request(
            user,
            &state,
            GooseMethod::Delete,
            None,
            true,
            "delete session",
            ExpectedStatus::SessionDeleted,
        )
        .await?;
        let state = session_mut(user)?;
        state.session_id = None;
        state.ready = false;
        state.callable_tools.clear();
        Ok(())
    })
}

mod transaction_future {
    use std::future::Future;
    use std::pin::Pin;

    use goose::prelude::TransactionResult;

    pub type TransactionFuture<'a> = Pin<Box<dyn Future<Output = TransactionResult> + Send + 'a>>;
}

async fn dormant_user() -> TransactionResult {
    tokio::time::sleep(std::time::Duration::from_millis(10)).await;
    Ok(())
}

fn session(user: &GooseUser) -> std::result::Result<&UserSession, Box<TransactionError>> {
    user.get_session_data::<UserSession>()
        .ok_or_else(|| custom_error("Goose user is missing MCP session state"))
}

fn session_mut(
    user: &mut GooseUser,
) -> std::result::Result<&mut UserSession, Box<TransactionError>> {
    user.get_session_data_mut::<UserSession>()
        .ok_or_else(|| custom_error("Goose user is missing MCP session state"))
}

fn next_request(
    user: &mut GooseUser,
) -> std::result::Result<(UserSession, Value), Box<TransactionError>> {
    let state = session_mut(user)?;
    let request_id = state.next_request_id;
    state.next_request_id = state
        .next_request_id
        .checked_add(1)
        .ok_or_else(|| custom_error("MCP request ID overflow"))?;
    Ok((state.clone(), json!(request_id)))
}

fn next_tool_call(
    user: &mut GooseUser,
) -> std::result::Result<(UserSession, Value, String), Box<TransactionError>> {
    let state = session_mut(user)?;
    if state.callable_tools.is_empty() {
        return Err(custom_error("Goose user has no safe callable MCP tools"));
    }
    let tool_index = state.next_tool % state.callable_tools.len();
    state.next_tool = (tool_index + 1) % state.callable_tools.len();
    let name = state.callable_tools[tool_index].clone();
    let request_id = state.next_request_id;
    state.next_request_id = state
        .next_request_id
        .checked_add(1)
        .ok_or_else(|| custom_error("MCP request ID overflow"))?;
    Ok((state.clone(), json!(request_id), name))
}

fn request_payload(
    state: &UserSession,
    method: &str,
    params: Option<Value>,
    request_id: Value,
) -> Value {
    if is_stateless_protocol(&state.protocol_version) {
        stateless_jsonrpc_with_id(method, params, request_id, &state.protocol_version)
    } else {
        jsonrpc_with_id(method, params, request_id)
    }
}

async fn send_mcp_request(
    user: &mut GooseUser,
    state: &UserSession,
    method: GooseMethod,
    payload: Option<&Value>,
    include_session: bool,
    request_name: &'static str,
    expected_status: ExpectedStatus,
) -> std::result::Result<McpResponse, Box<TransactionError>> {
    let mut request_builder = user
        .get_request_builder(&method, &state.endpoint)?
        .bearer_auth(state.bearer_token.expose())
        .header("accept", ACCEPT);
    if let Some(payload) = payload {
        request_builder = request_builder
            .header("content-type", "application/json")
            .body(payload.to_string());
    }
    if is_stateless_protocol(&state.protocol_version) {
        request_builder =
            request_builder.header("mcp-protocol-version", state.protocol_version.as_str());
        if let Some(method) = payload
            .and_then(|payload| payload.get("method"))
            .and_then(Value::as_str)
        {
            request_builder = request_builder.header("mcp-method", method);
            if let Some(name) = routing_name(method, payload.and_then(|value| value.get("params")))
            {
                request_builder = request_builder.header("mcp-name", name);
            }
        }
    } else if include_session {
        let session_id = state
            .session_id
            .as_deref()
            .filter(|value| !value.is_empty())
            .ok_or_else(|| custom_error("MCP request requires an initialized session"))?;
        request_builder = request_builder
            .header("mcp-session-id", session_id)
            .header("mcp-protocol-version", state.protocol_version.as_str());
    }

    let request = GooseRequest::builder()
        .method(method)
        .path(state.endpoint.as_str())
        .name(request_name)
        .set_request_builder(request_builder)
        .build();
    let response = user.request(request).await?;
    let mut request_metric = response.request;
    let response = match response.response {
        Ok(response) => response,
        Err(source) => return Err(Box::new(TransactionError::Reqwest(source))),
    };
    let status = response.status();
    let headers = response.headers().clone();
    if state.require_dataplane_backend
        && let Some(tag) = BackendIdentity::from_headers(&headers).dataplane_error()
    {
        return fail_request(user, &mut request_metric, tag);
    }
    let body = match bounded_response_body(response).await {
        Ok(body) => body,
        Err(_) => {
            return fail_request(
                user,
                &mut request_metric,
                "MCP response body was invalid or exceeded the safe size limit",
            );
        }
    };
    let accepted = match expected_status {
        ExpectedStatus::Ok => status == StatusCode::OK,
        ExpectedStatus::Accepted => status == StatusCode::ACCEPTED,
        ExpectedStatus::SessionDeleted => {
            status.is_success()
                || matches!(
                    status,
                    StatusCode::NOT_FOUND | StatusCode::METHOD_NOT_ALLOWED
                )
        }
    };
    if !accepted {
        return fail_request(
            user,
            &mut request_metric,
            "MCP response returned an unexpected HTTP status",
        );
    }
    if matches!(expected_status, ExpectedStatus::Accepted) && !body.is_empty() {
        return fail_request(
            user,
            &mut request_metric,
            "MCP notification response must not contain a body",
        );
    }
    if matches!(expected_status, ExpectedStatus::SessionDeleted) && !status.is_success() {
        user.set_success(&mut request_metric)?;
    }

    Ok(McpResponse {
        request: request_metric,
        headers,
        body,
    })
}

fn decode_result(
    response: &McpResponse,
    expected_id: &Value,
) -> std::result::Result<Value, &'static str> {
    let content_type = response
        .headers
        .get(CONTENT_TYPE)
        .and_then(|value| value.to_str().ok())
        .ok_or("MCP response is missing a valid Content-Type")?;
    let message = parse_mcp_body(&response.body, content_type)
        .map_err(|_| "MCP response body is not valid JSON or SSE")?
        .ok_or("MCP response does not contain a JSON-RPC message")?;
    if message.get("jsonrpc").and_then(Value::as_str) != Some("2.0") {
        return Err("MCP response has an invalid JSON-RPC version");
    }
    if message.get("id") != Some(expected_id) {
        return Err("MCP response JSON-RPC ID does not match the request");
    }
    if message.get("error").is_some() {
        return Err("MCP response contains a JSON-RPC error");
    }
    message
        .get("result")
        .cloned()
        .ok_or("MCP response is missing its JSON-RPC result")
}

fn fail_request<T>(
    user: &mut GooseUser,
    request: &mut GooseRequestMetric,
    tag: &'static str,
) -> std::result::Result<T, Box<TransactionError>> {
    match user.set_failure(tag, request, None, None) {
        Err(error) => Err(error),
        Ok(()) => Err(custom_error(tag)),
    }
}

fn custom_error(message: &str) -> Box<TransactionError> {
    Box::new(TransactionError::Custom(message.to_owned()))
}

async fn inspect_reports(
    reports: &GooseReportPaths,
    bearer_token: &str,
    metrics: &GooseMetrics,
) -> std::result::Result<(), GooseRunError> {
    let mut first_inspection_error = None;
    let mut tainted = Vec::new();
    for path in [&reports.html, &reports.json] {
        match tokio::fs::read(path).await {
            Ok(contents) if contains_bytes(&contents, bearer_token.as_bytes()) => {
                tainted.push(path.clone());
            }
            Ok(_) => {}
            Err(source) if first_inspection_error.is_none() => {
                first_inspection_error = Some((path.clone(), source));
            }
            Err(_) => {}
        }
    }
    let first_tainted = tainted.first().cloned();
    let mut cleanup_error = None;
    for path in tainted {
        if let Err(source) = tokio::fs::remove_file(&path).await
            && cleanup_error.is_none()
        {
            cleanup_error = Some((path, source));
        }
    }
    if let Some((path, source)) = cleanup_error {
        return Err(GooseRunError::ReportCleanup {
            path,
            source,
            metrics: Box::new(metrics.clone()),
            reports: reports.clone(),
        });
    }
    if let Some(path) = first_tainted {
        return Err(GooseRunError::CredentialLeak {
            path,
            metrics: Box::new(metrics.clone()),
            reports: reports.clone(),
        });
    }
    if let Some((path, source)) = first_inspection_error {
        return Err(GooseRunError::ReportInspection {
            path,
            source,
            metrics: Box::new(metrics.clone()),
            reports: reports.clone(),
        });
    }
    Ok(())
}

async fn bounded_response_body(mut response: reqwest::Response) -> Result<String> {
    let mut body = Vec::new();
    while let Some(chunk) = response
        .chunk()
        .await
        .context("failed to read MCP response body")?
    {
        if chunk.len() > MAX_RESPONSE_BODY_BYTES.saturating_sub(body.len()) {
            bail!("MCP response body exceeded {MAX_RESPONSE_BODY_BYTES} bytes");
        }
        body.extend_from_slice(&chunk);
    }
    String::from_utf8(body).context("MCP response body is not valid UTF-8")
}

fn contains_bytes(contents: &[u8], needle: &[u8]) -> bool {
    !needle.is_empty()
        && contents
            .windows(needle.len())
            .any(|window| window == needle)
}

fn normalized_host(value: &str) -> Result<String> {
    let mut url = Url::parse(value).context("invalid MCP_CLI_BASE_URL for Goose")?;
    if !matches!(url.scheme(), "http" | "https") || url.host().is_none() {
        bail!("MCP_CLI_BASE_URL must be an HTTP(S) URL with a host");
    }
    if !url.username().is_empty() || url.password().is_some() {
        bail!("MCP_CLI_BASE_URL must not contain credentials");
    }
    if url.query().is_some() || url.fragment().is_some() {
        bail!("MCP_CLI_BASE_URL must not contain a query or fragment");
    }
    url.set_path("/");
    Ok(url.into())
}

fn dataplane_endpoint(server_id: &str) -> Result<String> {
    let mut url = Url::parse("http://integration.invalid/")
        .context("failed to initialize dataplane endpoint URL")?;
    url.path_segments_mut()
        .map_err(|()| anyhow::anyhow!("failed to build dataplane endpoint"))?
        .extend(["servers", server_id, "mcp"]);
    Ok(url.path().to_owned())
}

fn goose_run_time(value: &str) -> Result<String> {
    let bytes = value.as_bytes();
    let mut position = 0;
    let mut total_millis = 0_u128;
    while position < bytes.len() {
        let number_start = position;
        while position < bytes.len() && bytes[position].is_ascii_digit() {
            position += 1;
        }
        let amount = value[number_start..position]
            .parse::<u128>()
            .context("invalid Goose run time")?;
        let multiplier = if bytes[position..].starts_with(b"ms") {
            position += 2;
            1
        } else {
            let unit = bytes
                .get(position)
                .copied()
                .context("invalid Goose run-time unit")?;
            position += 1;
            match unit {
                b's' => 1_000,
                b'm' => 60_000,
                b'h' => 3_600_000,
                b'd' => 86_400_000,
                _ => bail!("invalid Goose run-time unit"),
            }
        };
        total_millis = total_millis
            .checked_add(
                amount
                    .checked_mul(multiplier)
                    .context("Goose run time is too large")?,
            )
            .context("Goose run time is too large")?;
    }
    let seconds = total_millis.div_ceil(1_000);
    if seconds == 0 {
        bail!("Goose run time must be greater than zero");
    }
    let seconds = usize::try_from(seconds).context("Goose run time is too large")?;
    Ok(format!("{seconds}s"))
}

fn failed_request_count(metrics: &GooseMetrics) -> usize {
    metrics
        .requests
        .values()
        .map(|request| request.fail_count)
        .sum()
}

fn failed_transaction_count(metrics: &GooseMetrics) -> usize {
    metrics
        .transactions
        .iter()
        .flatten()
        .map(|transaction| transaction.fail_count)
        .sum()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn report_audit_removes_every_tainted_output_before_failing() {
        let directory = tempfile::tempdir().expect("temporary report directory");
        let reports = GooseReportPaths {
            html: directory.path().join("goose.html"),
            json: directory.path().join("goose.json"),
        };
        let token = "credential-present-in-both-reports";
        tokio::fs::write(&reports.html, format!("html {token}"))
            .await
            .expect("HTML report should be written");
        tokio::fs::write(&reports.json, format!("json {token}"))
            .await
            .expect("JSON report should be written");

        let error = inspect_reports(&reports, token, &GooseMetrics::default())
            .await
            .expect_err("credential-bearing reports must fail closed");

        assert!(matches!(error, GooseRunError::CredentialLeak { .. }));
        assert!(!reports.html.exists());
        assert!(!reports.json.exists());
    }
}
